const AWS = require('aws-sdk');

// AWS Configuration
AWS.config.update({
  region: process.env.DYNAMODB_REGION,
  endpoint: process.env.DYNAMODB_ENDPOINT,
  accessKeyId: process.env.AWS_ACCESS_KEY_ID,
  secretAccessKey: process.env.AWS_SECRET_ACCESS_KEY
});

const dynamodb = new AWS.DynamoDB();
const docClient = new AWS.DynamoDB.DocumentClient();

// Wait for DynamoDB function
const waitForDynamoDB = async () => {
  console.log('Waiting for DynamoDB to be ready...');
  let retries = 30;
  
  while (retries > 0) {
    try {
      await dynamodb.listTables().promise();
      console.log('DynamoDB is ready!');
      return true;
    } catch (err) {
      console.log(`Waiting for DynamoDB... (${retries} retries left)`);
      retries--;
      await new Promise(resolve => setTimeout(resolve, 2000));
    }
  }
  throw new Error('DynamoDB failed to start');
};

// Initialize database tables
async function initializeDatabase() {
  console.log('Initializing database tables...');
  
  await waitForDynamoDB();
  
  try {
    // Create Users table with autogenerated UID
    await dynamodb.createTable({
      TableName: 'Users',
      KeySchema: [{ AttributeName: 'uid', KeyType: 'HASH' }],
      AttributeDefinitions: [ { AttributeName: 'uid', AttributeType: 'S' },
        { AttributeName: 'email', AttributeType: 'S' }],
        GlobalSecondaryIndexes: [
        {
          IndexName: 'EmailIndex',
          KeySchema: [{ AttributeName: 'email', KeyType: 'HASH' }],
          Projection: { ProjectionType: 'ALL' },
          BillingMode: 'PAY_PER_REQUEST'
        }
      ],
      BillingMode: 'PAY_PER_REQUEST'
    }).promise();
    console.log('Users table created with autogennerated UID');
  } catch (err) {
    if (err.code === 'ResourceInUseException') {
      console.log('Users table already exists');
    } else {
      console.error('Error creating Users table:', err);
    }
  }

  try {
    // Create UserMaps table with autogenerated UID
    await dynamodb.createTable({
      TableName: 'UserMaps',
      KeySchema: [{ AttributeName: 'uid', KeyType: 'HASH' },
        { AttributeName: 'mapId', KeyType: 'RANGE' }],
      AttributeDefinitions: [ { AttributeName: 'uid', AttributeType: 'S' },
        { AttributeName: 'mapId', AttributeType: 'S' }],
      BillingMode: 'PAY_PER_REQUEST'
    }).promise();
    console.log('UserMaps table created');
  } catch (err) {
    if (err.code === 'ResourceInUseException') {
      console.log('UserMaps table already exists');
    } else {
      console.error('Error creating UserStates table:', err);
    }
  }
}

module.exports = {
  dynamodb,
  docClient,
  initializeDatabase
};